SELECT @@resource_governor_cpu_limit_mode;
show resource pools;

CREATE RESOURCE POOL ingest WITH SOFT_CPU_LIMIT_PERCENTAGE = 25;
CREATE RESOURCE POOL rt WITH SOFT_CPU_LIMIT_PERCENTAGE = 50;
CREATE RESOURCE POOL nrt WITH SOFT_CPU_LIMIT_PERCENTAGE = 20;